openapi: 3.0.0
info:
  title: Water API
  description:
  version: 0.1.9

servers:
  - url: http://134.0.113.72:7777/water/
    description: Optional server description, e.g. Main (production) server
  - url: https://26ac-178-76-226-214.eu.ngrok.io/water/
    description: Optional server description, e.g. Internal staging server for testing

paths:
  /resetpassword:
    get:
      summary: Returns token.
      description:
      responses:
        '200':
          description: A user object.
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '403':
          description: Incorrect data entry.
        '404':
          description: Was not found.
        default:
          description: Unexpected error
