openapi: 3.0.0
info:
  title: Water API
  description:
  version: 0.1.9

servers:
  - url: http://134.0.113.72:7777/water/
    description: Optional server description, e.g. Main (production) server
  - url: https://26ac-178-76-226-214.eu.ngrok.io/water/
    description: Optional server description, e.g. Internal staging server for testing

paths:
  /sendphoto:
    post:
      summary: Create new meters data.
    description:
      responses:
        '200':
          description: A meters data object.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                    example: 4
                  name:
                    type: string
                    example: Jessica Smith
          '400':
            description: The specified user ID is invalid (not a number).
          '404':
            description: A user with the specified ID was not found.
          default:
            description: Unexpected error